# -*- coding: utf-8 -*-
"""1.2.현금흐름, 이자율과 시간가치.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1atYl1E5qmUy1hKZjUT8Pf43EG5TTX0O8
"""

#단리이자 계산
#단리이자 공식 : 원금 x(1+이율 x 기간)

#(1) 원금 : 1000만원
#(2) 이율 : 연간 5%
#(3) 기간 : 1년
#(4) 1년 후 인출액 = 1000만원 x(1+5% x1) = 10,500,000dnjs


#변수 a에 예금액을 입력한다.
a=1000

#1년간 이자 계산이 12회 이뤄지므로n=12이다.
n=12

#1년간 이자율5%를 12로 나눠 월간 이자율로 바꾼다.
#이자 계산도 월간, 이자율도 월간으로 일치시키는 것이다.
r = 0.05/n

#이자율 계산 횟수가 늘어났지만 게산 방법은 종전과 같다.
s_simple = a*(1+r*n)
print(s_simple)

