# -*- coding: utf-8 -*-
"""1.3.NPV와IRR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UZNby9CyddjYCzcOFeXCYnozedGB5TK_
"""

# cashflows : 현금흐름을 저장
# i : 횟수
# r : 이자율

cashflows = [12000, 15000, 18000, 21000, 26000]
i = 0
r = 0.015

#최초의 투자금&현금유출이기에 -로 표기.
npv = -70000

#cashfolws 리스트를 반복해 미래에 들어올 현금흐름을 할인한다.
#할인을 통해 현재가치로서 계산한 다음 npv변수에 누적.

for c in cashflows :
    i = i +1
    npv=npv + c/(1+r)**i

print(npv)

#scipy라이브러리 : 순현재가치를 계신하는 npv함수를 제공함.

#scipy 라이브러리를 이용한 계산.
#scipy 라이블러리를 sp라는 이름으로 임포트한다.

import scipy as sp

#현금흐름을 리스트로 만든다.
cashflows = [-70000, 12000, 15000, 18000, 21000, 26000 ]
r= 0.015

#npv함수로 순현재가치를 계산한다.
npv =sp.npv(r, cashflows)
print(npv)