# -*- coding: utf-8 -*-
"""1.5.자주사용하는통계량_기댓값,분산,공분산,상관계수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0jgz46jvrYxuR72t_szOkVDjPlRoAl-
"""

#산술평균-(1)파이썬의 표준함수로 처리.
nums =[1,2,3,4,5,6] #nums 리스트에 값을 저장.
print(sum(nums) / len(nums ) ) #sum함수로 합계를, len함수로 데이터의 개수를 구한다.

#산술평균-(2)numpy 라이브러리를 가져와서 처리.
import numpy as np
a = np.array( [1,2,3,4,5,6] ) #array()함수로 리스트를 array 객체로 저장한다.
print(a.mean() ) #객체의 mean()함수를 활용하여 평균을 계산.

#기대값을 계산한다.,
#기대값을 계산하려면 사건과, 사건이 일어날 확률을 가진 리스트가 각각 필요하다.
#리스트를 반복하는 동안 두 리스트(사건값 리스트, 확률값 리스트)에서 사건/확률을 하나씩 곱하고 더하면 된다.

#사건과 확률을 case와 prob 리스트에 저장한다.
case =[1,2,3,4,5,6]
prob =[1/6. 1/6, 1/6. 1/6. 1/6. 1/6]

#사건리스트와 확률리스트를 zip 함수로 묶고 for루프로 반복한다.
#ex변수 : 반복하는 동안 두 리스트에서 값을 받아 변수 c와 p에 저장하고 곱한 결과를 저장.
ex = 0.0

for c,p in zip(case, prob):
    ex = ex + c*p
print(ex)#결과를 출력한다.

#위 반복문은 아래와 같은 1줄 for문으로도 대체가능.
ex = sum(c*p for c,p in zip(case, prob))

#결과출력
print(ex)