# -*- coding: utf-8 -*-
"""9장_함등함수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kYv-_DuXXZQgQBRlmtEb4OCWlaSSmeut
"""

#9,1 항등함수
def identity_function(x):
  return x

#9.2 비례확률함수
import numpy as np
def mean_probabilaty(x):
  x=x.T
  return(x/np.sum(x, axis=0)).T

y = np.array([[1,1,3,0,0,0,1,0,0,4], [2,2,5,1,0,0,5,0,1,4]])
print(mean_probabilaty(y))

#9.3스프트맥스 함수
def softmax(X):
  X = X.T - np.max(X.T, axis=0)
  return (np.exp(X) / np.sum(np.exp(X), axis=0)).T

softmax(np.array([[1,1,2,4,6,0,0,0,0,0]]))

