# -*- coding: utf-8 -*-
"""D.1.1. statsmodels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ELYu02-QgSUsnALjazzPqSN13qE4Rf2v
"""

#D.1.1. statsmodels
#statsmodels : 사용자가 데이터를 탐색할 때 다양한 통계 테스트를 수행할 수 있는 파이썬 라이브러리.
#              사이파이에서 제공하는 통계 모듈을 보완한다. 

#pip install statsmodels #책(359)에서는 왼쪽의 명령어로 설치가능하다고 하는데 문법에러난다. -_-;#                       

import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

#간단한 통계분석 예제

#load data
dat = sm.datasets.get_rdataset("Guerry", "HistData").data

#Fit regression model (using the natural log of one of the regressors)
results = smf.ols('Lottery ~ Literacy + np.log(Pop1831)', data=dat).fit()

#Insprct the results
print(results.summary())