# -*- coding: utf-8 -*-
"""chapter7_금융공학모델링.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XandXZj2qeySDi90fKE-_rDJikDuWLhU
"""

#7.1S&P500 vs KOSPI200비교
#각 지수출처
#S&P500 : 네이버
#KOSPI200 : 다음

#[참고]각 포털별 금융시세 정보 제공여부 및 장단점.
#구글(불가)-2018년부터 금융시세정보 데이터정보수집 차단.
#야후 파이낸스(가능)-미국, 유럽시장의 금융시세정보 좋음. 단 한국시장정보는 누락이 많음.
#네이버&다음(가능)-국내외 금융정보를 제공해주는 것은 좋은데 포맷이 달라서 일일이 만들어줘야 함.

#네이버에서 KOSPI200 지수 수집하기(HTML 페이지 크롤링)
#대상링크 : http://finance.naver.com/sise/sise_index.nhn?code=KOSPI200
#           위의 링크에서 KOSPI200지수 정보가 출력(레이아웃이 그때마다 달라질수 있음)