# -*- coding: utf-8 -*-
"""예1_str타입의 문자를 datetime형식으로 바꾸기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134sLUrgimjgkskiawPAUtu6bli6VogF9
"""

#책 페이지 2장-45페이지
import datetime
format = '%Y-%m-%d %H:%M:%S'

datetime_str = '2018-05-13 12:34:56'
datetime_dt = datetime.datetime.strptime(datetime_str, format)

print(type(datetime_dt))
print(datetime_dt)