# -*- coding: utf-8 -*-
"""예1_str타입의 문자를 datetime형식으로 바꾸기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134sLUrgimjgkskiawPAUtu6bli6VogF9
"""

#책 페이지 2장-45페이지
#str 타입문자 → datetime로 변환
import datetime
format = '%Y-%m-%d %H:%M:%S'

datetime_str = '2018-05-13 12:34:56'
datetime_dt = datetime.datetime.strptime(datetime_str, format)

print(type(datetime_dt))
print(datetime_dt)

#책 페이지 2장-45페이지
#datetime →str 타입문자로 변환
datetime_str = datetime_dt.strftime('%Y-%m-%d %H:%M:%S')
print(type(datetime_str))
print(datetime_str)

#48페이지
#str 타입읜 ISO 8601 형식에 맞춰서 사용해야 합니다.
import numpy as np
np.datetime64('2019-01-01')

numpy.datetime64('2019-01-01')

import numpy as np
print( np.datetime64(1000,'ns') )
print( np.datetime64(10000,'D') )
print( np.datetime64(10000000,'s') )

np.array(['2007-07-13','2006-01-13','2010-08-13'],
        dtype='datetiem64[D]')

#49페이지
np.arange('2005-02', '2005-03', dtype='datetime64{D]')