# -*- coding: utf-8 -*-
"""4_0벡터와 행렬 개요.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1luhAAx5EjsBavEQvnADYLsLaSqEZ9yWN
"""

#필요한 패키지

import numpy as np
import scipy

from scipy import linalg as la
import matplotlib.pyplot as plt

#버전 확인
print(np.__version__)
print(scipy.__version__)