# -*- coding: utf-8 -*-
"""4_3 선형방정식.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kK8aSecpaaAbPRBWoL0H19dMG0xK_z8V
"""

#필요한 패키지(4_0에서 나오는 기본 패키지)

import numpy as np
import scipy

from scipy import linalg as la
import matplotlib.pyplot as plt

#버전 확인
print(np.__version__)
print(scipy.__version__)

#4.3.1. QR분해

#4.3.1.1. 선형방정식과 후방대입법

A = np.array([[1,1], [1/2, -1]])

XTX = A.T@A

XTX

#출력결과
#array([[1.25, 0.5 ],
#       [0.5 , 2.  ]])

#-------------------------------------

#4.3.1.2. QR분해
Q,R = la.qr([[-1.35, -1.21],
             [0. , 1.67]])

R.round(2)

#출력결과
#array([[-1.35, -1.21],
#       [ 0.  ,  1.67]])







