# -*- coding: utf-8 -*-
"""코드13-1 초음파 광물 예측하기 : 데이터 확인과 실행.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p1RaT9Aq9KP_0px8TA07gmI1m3BgC7v3
"""

from keras.models import Sequential
from keras.layers.core import Dense
from sklearn.preprocessing import LabelEncoder

import pandas as pd
import numpy
import tensorflow as tf

#seed값 설정
numpy.random.seed(3)
tf.random.set_seed(3)

#데이터 입력
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/모두의 딥러닝(개정2판)/dataset/sonar.csv',header=None)

dataset = df.values
X = dataset[:,0:60]
Y_obj = dataset[:,60]

#문자열 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

#모델 설정
model = Sequential()
model.add(Dense(24, input_dim=60, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

#모델 컴파일
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#모델 실행

X = numpy.asarray(X).astype(numpy.float32)
Y = numpy.asarray(Y).astype(numpy.float32)
# 위의 2줄은 ValueError를 해결하기 위해 구글링해서 찾은 방법이다. 저자는 대체 뭘한거냐
#ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).



model.fit(X, Y, epochs=200, batch_size=5)

#결과 출력
print("\n Accuracy: %.4f" % (model.evaluate(X, Y)[1]))