# -*- coding: utf-8 -*-
"""코드11-1파마 인디언의 당뇨병 예측하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_tyyI5LejZrbFdbeJGUgu5jv-44ArJZ
"""

#코드11-1파마 인디언의 당뇨병 예측하기

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

import numpy
import tensorflow as tf

#seed값 생성
numpy.random.seed(3)
tf.random.set_seed(3)

#데이터 로드
dataset = numpy.loadtxt("/content/drive/MyDrive/Colab Notebooks/모두의 딥러닝(개정2판)/dataset/pima-indians-diabetes.csv", delimiter=",")
X = dataset[:,0:8]
Y = dataset[:,8]

#모델의 설정
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

#모델 컴파일 
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#모델실행
model.fit(X,Y, epochs=200, batch_size=10)
print("\n Accuracy:%.4f" % (model.evaluate(X,Y)[1] ) )

