# -*- coding: utf-8 -*-
"""코드18-2 lstm과 cnn을 조합해 영화리뷰 분류하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oavr8aVREl4LcF3fI-j4vWiqXPVFo2Bs
"""

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import LSTM
from keras.layers import Conv1D, MaxPooling1D
from keras.dataset import imdb

import numpy
import tensorflow as tf
import matplotlib.pyplot as plt