# -*- coding: utf-8 -*-
"""코드3-1선형회귀실습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6TM6eryF75nCw_dYgXT5jaqRJL1l4UR
"""

import numpy as np

#x값과  y값 설정
x=[2,4,6,8]
y=[81,93,91,97]

#x와 y의 평균값
mx = np.mean(x)
my = np.mean(y)
print("x의 평균값 : ", mx)
print("y의 평균값 : ", my)

#기울기 공식의 분모
divisor =sum([ (mx-i)** 2 for i in x ])

#기울기 공식의 분자
def top(x, mx, y, my):
    d =0
    for i in range(len(x)):
        d += (x[i] - mx)* (y[i] - my)
    return d

dividend = top(x, mx, y, my)

print("분모 : ", divisor )
print("분자 : ", dividend )

#기울기와 y절편 구하기
a = dividend / divisor
b = my - ( mx * a ) 

#출력으로 확인
print("기울기 a =",a)
print("y절편  b =",b)